"""
Simulation-only: build a HoloSystem with known random parameters, to serve
as ground truth. The twin is then trained purely on (hologram -> camera
image) pairs generated by this frozen model, exactly as it would be trained
on real captures.
"""
from dataclasses import dataclass
from typing import Optional

import numpy as np
import torch

from src.twin.model import OpticsGeometry, HoloSystem, AberrCoefficients, ModuleFlags
from src.training.build_twin import get_smooth_field
from src.io.base_config import BaseConfig
from src.training.zernike import Zernike


# --------------------------------------------------------------------------
# Config
# --------------------------------------------------------------------------

@dataclass
class GroundTruthConfig(BaseConfig):
    """
    The random parameters used to build a simulated ground-truth
    HoloSystem (see build_ground_truth below). Used by
    pipelines/sim/run_training.py to build a fresh one each run.
    """
    crosstalk_sigma: tuple = (0.5, 0.5)
    pixel_fill: tuple = (0.95, 0.95)
    deadspace_reflectance: float = 0.9
    lut_scale: float = 4.4 * np.pi
    num_pupil_tiles: int = 20
    background_reflectance: float = 0.3
    affine_params: Optional[dict] = None   # None -> a fixed, mildly-misaligned default (see build_ground_truth)

    module_flags: Optional[ModuleFlags] = None   # which modules are present in the ground truth
    use_crosstalk_fast_approx: bool = False
    use_pupil_vignetting: bool = False
    ideal_affine: bool = False    # True -> zero rotation/shift, unit scale (overrides affine_params)
    no_tip_tilt: bool = True      # zero out the tip/tilt Zernike terms in both generated fields
    aberr_scale: float = 15.0
    field_zernike_scale: float = 10.0
    background_zernike_scale: float = 10.0

    seed: Optional[int] = None    # numpy random seed for reproducible ground-truth parameters


# --------------------------------------------------------------------------
# Build
# --------------------------------------------------------------------------

def build_ground_truth(
    geometry: OpticsGeometry,
    crosstalk_sigma: tuple = (0.5, 0.5),
    slm_field_noise_mag: float = 0.1,
    slm_field_scale: float = 1.0,
    deadspace_reflectance: float = 0.9,
    lut_scale: float = 4.4 * np.pi,
    num_pupil_tiles: int = 20,
    background_reflectance: float = 0.3,
    affine_params: Optional[dict] = None,

    module_flags: Optional[ModuleFlags] = None,
    use_crosstalk_fast_approx: bool = False,
    use_pupil_vignetting: bool = False,
    ideal_affine: bool =   False,
    no_tip_tilt: bool =    True,
    aberr_scale: float =   15.0,    # Seidel coefficients drawn from +/- aberr_scale/2, rad
    slm_field_sigma = 1.0,  # fraction of SLM width
    field_zernike_scale: float = 10.0,   # SLM-field Zernikes, +/- scale/2, rad
    background_zernike_scale: float = 10.0,
    lut_depth_grid_divisor: int = 20,
    use_lut_depth: bool = False,

    seed: int = None,
) -> HoloSystem:
    """
    Returns a frozen HoloSystem with randomized ground-truth parameters.
    """
    if seed is not None:
        np.random.seed(seed)

    slm_shape = geometry.slm_pixels

    zernike_coeffs = (np.random.rand(15) - 0.5) * field_zernike_scale
    if no_tip_tilt:
        zernike_coeffs[1] = 0.0  # Tip
        zernike_coeffs[2] = 0.0  # Tilt
    E_in_true = get_smooth_field(
        slm_shape,
        zernike_coeffs=zernike_coeffs,
        amp_gauss_sigma=slm_field_sigma,  # fraction of SLM width
        noise_phase_mag=slm_field_noise_mag,
        noise_amp_mag=slm_field_noise_mag,
    ) * slm_field_scale

    zernike_coeffs = (np.random.rand(15) - 0.5) * background_zernike_scale

    if no_tip_tilt:
        zernike_coeffs[1] = 0.0  # Tip
        zernike_coeffs[2] = 0.0  # Tilt
    E_back_true = get_smooth_field(
        geometry.far_fov_samples,
        zernike_coeffs=zernike_coeffs,
        amp_gauss_sigma=0.5,
        noise_phase_mag=slm_field_noise_mag,
        noise_amp_mag=slm_field_noise_mag,
    ) 
    # Decrease reflectance in the background, to simulate dust/fringes/etc.
    E_back_true = E_back_true * background_reflectance

    # Zero out the central SLM-aperture-sized region, then IFFT: this models
    # the background as originating from structure *outside* the active SLM
    # aperture (dust/fringes).
    Mf, Nf = geometry.far_fov_samples
    P, Q = slm_shape
    E_back_true[Mf // 2 - P // 2: Mf // 2 + P // 2, Nf // 2 - Q // 2: Nf // 2 + Q // 2] = 0
    E_back_true = torch.fft.fftshift(torch.fft.ifft2(torch.fft.ifftshift(E_back_true), norm="ortho"))

    aberr_coeffs_true = AberrCoefficients(*(np.random.rand(6) - 0.5) * aberr_scale)

    if use_lut_depth:
        shape=(geometry.slm_pixels[0] // lut_depth_grid_divisor, geometry.slm_pixels[1] // lut_depth_grid_divisor)
        lut_depth = get_smooth_depth(
            shape=shape,
            zernike_coeffs=(np.random.rand(15) - 0.5) * 10,
            depth_scale=0.2,
            remove_ramp=True,
        )

    model_true = HoloSystem(
        geometry=geometry,
        slm_field_init_field=E_in_true,
        crosstalk_init_sigma=crosstalk_sigma,
        crosstalk_pixel_samples=3,
        crosstalk_fast_approx=use_crosstalk_fast_approx,
        crosstalk_use_residual=False,
        pixel_init_deadspace_reflectance=deadspace_reflectance,
        pupil_init_coeffs=aberr_coeffs_true,
        pupil_num_tiles=num_pupil_tiles,
        lut_init_scale=lut_scale,
        pupil_use_vignetting=use_pupil_vignetting,
        background_init_field=E_back_true,
        lut_use_depth=use_lut_depth,
        lut_depth_grid_divisor=lut_depth_grid_divisor,
        lut_init_depth_map=lut_depth if use_lut_depth else None,
    )

    if ideal_affine:
        affine_params_true = {"rotation": 0.0, "scale": (1.0, 1.0), "shift": (0.0, 0.0)}
    else:
        if affine_params is not None:
            affine_params_true = affine_params
        else:
            rot_rad = np.radians(4.0) # convert degrees to radians
            affine_params_true = {"rotation": rot_rad, "scale": (1.02, 0.97), "shift": (2.0, 5.0)}
    model_true.camera.affine_params = affine_params_true

    # Disable desired modules
    model_true.set_active(default=True, flags=module_flags)

    # Freeze all parameters; this is the static ground truth model.
    model_true.set_unfrozen(default=False)

    return model_true


def get_smooth_depth(
    shape: tuple,
    zernike_coeffs: Optional[np.ndarray] = None,
    depth_scale: float = 0.2,
    remove_ramp: bool = True,
) -> torch.Tensor:
    """
    Build a smooth depth map on the SLM plane via Zernike terms.

    Returns
    -------
    torch.Tensor  float32, shape slm_pixels/lut_depth_grid_divisor
    """
    num_zernikes = 15
    zernike = Zernike(slm_shape=shape, num_zernikes=num_zernikes)

    if remove_ramp and zernike_coeffs is not None:
        _zernike_coeffs = np.copy(zernike_coeffs)
        _zernike_coeffs[0] = 0.0 # remove piston
        _zernike_coeffs[1] = 0.0 # remove y-tilt
        _zernike_coeffs[2] = 0.0 # remove x-tilt

    else:
        _zernike_coeffs = zernike_coeffs

    # --- phase ---
    depth = zernike.get_phase(_zernike_coeffs)

    # normalise the range to [1-depth_scale, 1+depth_scale]
    depth = (depth - np.min(depth)) / (np.max(depth) - np.min(depth)) * (2 * depth_scale) + (1 - depth_scale)

    return torch.tensor(depth, dtype=torch.float)